
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.name="josue"
    vb.memory = "1024"
    vb.cpus = "2"
    # Fichero a disco
    file_to_disk = 'tmp/disk.vdi'
     # Comrueba si existe
     unless File.exist?(file_to_disk)
       #customize (comando de Vboxmanage)
       vb.customize ['createhd',
                     '--filename', file_to_disk,
                     '--size', 500 * 1024]
     end
     vb.customize ['storageattach', :id,
                   '--storagectl', 'SATAController',
                   '--port', 1,
                   '--device', 0,
                   '--type', 'hdd',
                   '--medium', file_to_disk]
  end
end
